theme: jekyll-theme-architect
title: Keerthi Raj Kunniyoor
description: Doctoral Candidate, IIT-Kharagpur, India
tagline: Contact - keerthirajkunniyoor@iitkgp.ac.in
github:
  is_user_page: false
  is_project_page: false
