theme: jekyll-theme-architect
title: Keerthi Raj Kunniyoor
tagline: Doctoral Candidate, IIT-Kharagpur, India
description: Contact - keerthirajkunniyoor@gmail.com
github:
  is_user_page: false
  is_project_page: false
